# Generated by Django 3.1.3 on 2020-11-23 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Exam_Name', models.CharField(max_length=100)),
                ('Client_Name', models.CharField(max_length=100)),
                ('Mock_Start_Date', models.DateField()),
                ('Mock_End_Date', models.DateField()),
                ('Exam_Start_Date', models.DateField()),
                ('Exam_End_Date', models.DateField()),
                ('Number_of_Regions', models.IntegerField()),
                ('Number_of_Exam_Centers', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='ExamDetails',
        ),
    ]
